# Which language file to use
language: en_us

# How many breweries per player
brewery-limit: 3

# notify player when their brew has finished
notify-player: false

# Enable qualities
# When you change this, it will break the already brewed drinks
qualities: true