main: com.huskydreaming.medieval.brewery.MedievalBreweryPlugin
name: MedievalBrewery
api-version: '1.20'
version: 1.2
author: HuskyDreaming
load: POSTWORLD
soft-depend:
  - Multiverse-Core
  - WorldGuard
  - Oraxen